[build]
  command = "npm run build:netlify"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[dev]
  framework = "vite"
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  autoLaunch = true
